name: PR AI Summarizer
description: Returns generative AI PR Summary from PR commits in context.
author: Philip De Lorenzo <philip.delorenzo@gmail.com>

branding:
    icon: "check-circle"
    color: "green"

inputs:
    github_token:
        description: "The Github Token needed to run functions in the repo - use {{ secrets.GH_TOKEN }} from your repo secrets."
        required: true
        default: None

    claude_api_token:
        description: "The Claude API Token needed to run functions in the repo - use {{ secrets.CLAUDE_API_KEY }} from your repo secrets."
        required: true
        default: None

runs:
    using: "composite"
    steps:
        - name: Debug Environment
          run: |
              echo -e "\u001b[36m Debug Information\u001b[0m"
              echo "::group:: Debug Data"
              echo "Current User: $(whoami)"
              echo "Workspace: $GITHUB_WORKSPACE"
              ls -la $GITHUB_WORKSPACE || echo "Workspace empty"
              echo "${{ github.head_ref }}"
              echo "::endgroup::"
              echo -e "\u001b[32m\xE2\x9C\x94\u001b[0m Debug Information\u001b[0m"
          shell: bash

        - name: Checkout code
          uses: actions/checkout@v4
          with:
              ref: ${{ github.head_ref }}
              token: ${{ inputs.github_token }}
              fetch-depth: 0

        - name: Get PR Diff
          id: get_diff
          run: |
              git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr_diff.txt
          shell: bash

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.13"

        - name: Install Dependencies
          run: |
              python -m pip install --upgrade pip
              pip install anthropic
          shell: bash

        - name: Run Claude PR Summary
          id: pr-summary
          env:
              GH_TOKEN: ${{ inputs.github_token }}
              CLAUDE_API_KEY: ${{ inputs.claude_api_token }}
          shell: bash
          run: |
              set -o pipefail
              python3 ${{ github.action_path }}/src/pr.py --file pr_diff.txt   
              # This reads summary.md and updates the PR - The file is created from the code above.
              gh pr edit ${{ github.event.pull_request.number }} --body-file summary.md
